### ISSUE TITLE
Template parse errors: 'ion-text-avatar' is not a known element

### ISSUE THREAD

**Issue by schifflm** [Airblader/ionic-text-avatar#1]
I have installed the ion-text-avatar as described and added it to the declarations array of app.module.ts.
But when I use <ion-text-avatar> in my page.html then I get following error message:
Uncaught (in promise): Error: Template parse errors:
'ion-text-avatar' is not a known element:
1. If 'ion-text-avatar' is an Angular component, then verify that it is part of this module.
2. If 'ion-text-avatar' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
      <ion-item>
        <ion-avatar item-start>
          [ERROR ->]<ion-text-avatar>M</ion-text-avatar>
        </ion-avatar>

Then I added CUSTOM_ELEMENTS_SCHEMA and NO_ERRORS_SCHEMA to @NgModule.schemas, but get still the same error message.

Could you please help with a hint, what I could do.
Thank you.
Best regards
Martin

**Comment by Airblader** [comment]
Yeah, sorry, I've noticed this as well. I'm not really sure what the setup would look like for a correct library and don't have the time to look into it (PRs welcome).

An easy workaround is to just copy the files into your project rather than trying to install it as a library.

**Comment by schifflm** [comment]
Now I found out what the problem is and have a solution for it:
I work with lazy loading and then I have to add to page.module.ts what you described for app.module.ts.
See my example of page.module.ts:
import { NgModule } from '@angular/core';
import { IonicPageModule } from 'ionic-angular';
import { IonTextAvatar } from 'ionic-text-avatar';
import { AnweisungenPage } from './anweisungen';

@NgModule({
  declarations: [
    AnweisungenPage,
    IonTextAvatar
  ],
  imports: [
    IonicPageModule.forChild(AnweisungenPage),
  ],
})
export class AnweisungenPageModule {} 

Thank you for your answer and may be my answer helps you and other guys using your very nice text-avatar.

**Comment by Airblader** [comment]
The issue I meant is actually #2, so closing this one.
