### ISSUE TITLE
typescript error when running "ionic cordova build android --prod --release"

### ISSUE THREAD

**Issue by DaemondShu** [Airblader/ionic-text-avatar#3]
[01:33:46]  typescript error : ......../app/app.module.ts(42,5):
            Error during template compile of 'AppModule' Function expressions are not supported in decorators in 'IonTextAvatar' 'IonTextAvatar' references 'IonTextAvatar' 'IonTextAvatar' references 'ɵ3' 'ɵ3' contains the error at ionic-text-avatar/dist/src/ion-text-avatar/ion-text-avatar.js.ts(22,22) Consider changing the function expression into an exported function.

But the ionic-text-avatar works on "ionic cordova build android --device"

**Comment by Airblader** [comment]
See #2. If someone knows what exactly has to be done, I'm happy about a PR.
